sanger/crawler

- crawler/main.py
> Fix variable initialisation

- README.md
Closes #28 
* add reporting section in README
> Gpl499 document report creation

- crawler/config/defaults.py
Closes #
* Wrong file MK_sanger_report_200614_0800.csv
> Bug - wrong data file today

- crawler/config/defaults.py
Bugfix - Exclude file wrong file
> Add another file to the black list

- crawler/config/defaults.py
Add another file to black list
> Bug - another file to black list

- crawler/config/defaults.py
> Temporarily disable CBAZ

- crawler/config/defaults.py
- crawler/config/test.py
- tests/files/CAMC/CB_sanger_report_200503_2338.csv
- tests/files/CBAZ/CB_sanger_report_200503_2338.csv
Also commented out CAMC config as temporarily disabled in prod
Closes #61
> Changed Cambridge-az cog id from CBAZ to CAMC,

- crawler/config/defaults.py
> Added file to blacklist for Alderley

- crawler/config/defaults.py
> Added file to Alderley blacklist AP_sanger_report_200724_0001.csv

- crawler/config/defaults.py
> Develop to master

- crawler/config/defaults.py
> Update alderley black list

- crawler/migration_script.py
- migrate_sample_timestamps.py
- migrations/helpers/sample_timestamps_helper.py
- migrations/sample_timestamps.py
- run_migration.py
- tests/migrations/test_sample_timestamps.py
- tests/test_migration.py
> Gpl 593 sample timestamp migration

- migrations/helpers/mlwh_samples_update_helper.py
oops, need the read write user here
> GPL-579 fix 

- crawler/db.py
> GPL642_654 Reduced the ROWS_PER_QUERY value

- crawler/config/defaults.py
- crawler/config/integration_with_blacklist_change.py
- crawler/config/test.py
> Replace whitespace with underscores in biomek labware class names

- .github/workflows/ci_docker.yml
> Add wildcard for tag realeses of docker images

- .github/workflows/ci_docker.yml
> Merge develop into master

- crawler/config/test.py
- crawler/constants.py
- migrations/helpers/shared_helper.py
- migrations/helpers/update_legacy_filtered_positives_helper.py
- setup_test_db.py
- tests/conftest.py
- tests/migrations/helpers/test_shared_helper.py
- tests/migrations/helpers/test_update_legacy_filtered_positives_helper.py
* Add to the `get_cherrypicked_samples` method a query to identify samples that have been cherrypicked by the Beckman workflow.
* Also lots of tesst to check the complexities
> Gpl 770 beckman cherrypicked samples

- .github/workflows/ci_docker.yml
- .github/workflows/ci_python.yml
- crawler/config/defaults.py
remove mysql root password from ci builds to match most people's local dev setups
> CI MySQL root password change

- crawler/config/defaults.py
- migrations/helpers/dart_samples_update_helper.py
- migrations/helpers/shared_helper.py
- migrations/helpers/update_filtered_positives_helper.py
- migrations/update_dart.py
> Test migrations changes

- crawler/sql_queries.py
> Renamed view for new view_plate_map

- runner.py
schedule crawler at 7:30am as well as 01:00am, to catch some of the files uploaded in the early morning
Closes #222
> GPL-826 Second parse of LH SFTP at 7:30

- crawler/main.py
> Added index for lh_source_plate_uuid to samples collection

- crawler/main.py
> Add mongodb table index for lh_source_plate_uuid

- .github/dependabot.yml
- .github/workflows/automated_release.yml
- .github/workflows/ci.yml
> Housekeeping - Add dependabot v2

- crawler/db/mysql.py
- crawler/sql_queries.py
- setup_test_db.py
Closes https://github.com/sanger/crawler/issues/361
Inserts are going way too slowly in UAT on Crawler.  This SQL code attempts to reduce the load on the database when inserting new data.
> DPL-040: Improve efficiency of SQL code

- README.md
- dependencies/docker-compose.yml
- dependencies/rabbitmq.conf
Part of #https://github.com/sanger/crawler/issues/467
* Add RabbitMQ to Crawler dependencies and update README with information on these dependencies
> DPL-204 Add RabbitMQ dependency

- schema_poc/consumer.py
- schema_poc/producer.py
I know there are credentials in this PR, but they are a temporary user I wanted to check was working in training.  So nothing important.
The main thing here is that this is the pattern to use to access AMQP over SSL.
> Change schema PoC to use SSL

- schema_poc/.gitignore
- schema_poc/avro_rabbit_consumer.py
- schema_poc/avro_rabbit_producer.py
- schema_poc/credentials.py
- schema_poc/credentials_example.py
- schema_poc/hosts_example.py
- schema_poc/schema_registry.py
- schema_poc/test_consumer.py
- schema_poc/test_messages.py
- schema_poc/test_producer.py
* Demonstration of using proper authentication for RabbitMQ and posting to actual exchanges/queues as will be deployed on production.
> DPL-204-1: Develop proof of concept

- Pipfile
- Pipfile.lock
- crawler/config/defaults.py
- crawler/helpers/cherrypicker_test_data.py
- tests/helpers/test_cherrypicker_data_helper.py
Bugfix - when creating testing data, baracoda fails on first request. This fix retries in crawler for 3 times before failing
> Add baracoda access retry

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- crawler/config/defaults.py
- schema_poc/credentials.py
- schema_poc/test_consumer.py
- schema_poc/test_producer.py
Just taking a stab at the issue we saw when pushing the updated Crawler up to UAT.  Honestly I wish I could explain why this is needed, but I'm struggling to find an answer.  I can't see how CENTRES was populated before this change and I wonder whether it was a side-effect of some code I've changed to the new MongoDB reading approach.
> DPL-203: Fix issues from uat

- crawler/config/defaults.py
This doesn't seem to trigger a linting issue about unused imports
> Import everything from centres.py

- .gitignore
- crawler/rabbit/async_consumer.py
Part of #544 
* Ensure that errors while connecting are actually logged.  (They were empty strings before)
* Add CA certificates to the SSL connection options.
> DPL-202: Display connection errors and add CA certificates to connection

- crawler/sql_queries.py
- migrations/back_populate_source_plate_and_sample_uuids.py
- tests/migrations/test_back_populate_source_plate_and_sample_uuids.py
> Fix check to use mongodb_ids instead of plate barcode

- README.md
- crawler/processing/update_sample_exporter.py
- schema_poc/test_messages.py
- schema_poc/test_timestamps.py
- tests/rabbit/messages/test_create_plate_message.py
- tests/testing_objects.py
Ensure timezones get handled correctly in Avro messages
> DPL-200: Fix bugs from testing

- crawler/config/development.py
- crawler/config/processors.py
- crawler/config/test.py
- crawler/processing/rabbit_message_processor.py
- dependencies/docker-compose.yml
- tests/processing/test_rabbit_message_processor.py
Changes to be able to setup processor by config
> Dpl361 02 setup processors config

- Dockerfile
A note has been made why this is necessary
Closes #
*
*
* ...
> Revert change to base image

- crawler/sql_queries.py
- migrations/back_populate_source_plate_and_sample_uuids.py
- migrations/helpers/shared_helper.py
Closes #798 
* Optimise database operations by using transactions on plates
> DPL-777: Further migration optimisations

- .github/dependabot.yml
Closes #
- 
_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
&nbsp; &nbsp; \- _Check story numbers included_  
&nbsp; &nbsp; \- _Check for debug code_  
&nbsp; &nbsp; \- _Check version_
> Add labels to dependabot configuration
